networks:
  minipress.net:
    driver: bridge
  back.net:
    driver: bridge

services:
  minipress.php:
    image: operrin/php:8.5.4
    command: sh -c "cd /var/www/src && php -S 0.0.0.0:80 -t /var/www/html /var/www/html/index.php"    
    ports:
      - "4490:80" #29029:80 sur Docketu
    volumes:
      - ./minipress.core/public:/var/www/html
      - ./minipress.core/src:/var/www/src
    working_dir: /var/www/src
    depends_on:
      - sql.data
    networks:
      - minipress.net

  minipress.web:
    image: httpd:2.4
    ports:
      - "3000:80" #29032:80 sur Docketu
    volumes:
      - ./minipress.web:/usr/local/apache2/htdocs/
    working_dir: /usr/local/apache2/htdocs/

  minipress.app:
    image: ghcr.io/cirruslabs/flutter:stable
    working_dir: /app
    command: >
      sh -c "
      [ -d web ] || flutter create . --platforms web &&
      flutter pub get &&
      flutter build web &&
      dart pub global activate dhttpd &&
      dart pub global run dhttpd --path build/web --port 8080 --host 0.0.0.0
      "
    ports:
      - "4491:8080"  #29033:80 sur Docketu
    volumes:
      - ./minipress.app/minipress_app:/app


  sql.data:
    image: mariadb:11.8.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6034:3306" #29031:3306 sur Docketu
    networks:
      minipress.net:
        aliases:
          - sql.db
      back.net:
        aliases:
          - sql.db

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_ARBITRARY: 1
    ports: 
      - "9001:80" #29030:80 sur Docketu
    networks:
      - back.net