-- Catégories
INSERT INTO `categorie` (`titre`) VALUES
('Technologie'),
('Culture'),
('Science');

-- Utilisateurs (mot de passe = "password" hashé bcrypt)
INSERT INTO `utilisateur` (`email`, `motdepasse`, `role`, `chemin_acces_img`, `pseudo`) VALUES
('jordan@minipress.fr', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 100, 'uploads/jordan.jpg', 'Jordan'),
('auriane@minipress.fr',   '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'uploads/auriane.jpg',   'Auriaaa');

-- Articles
INSERT INTO `article` (`titre`, `resume`, `contenu`, `date`, `id_categorie`, `id_utilisateur`) VALUES

-- Article 1 : catégorie Technologie (id=1), auteur id=1
('L\'essor de l\'intelligence artificielle générative',
 '**L\'IA générative** transforme en profondeur les secteurs créatifs et industriels. De ChatGPT à Midjourney, ces outils redéfinissent la frontière entre création humaine et machine.',
 '## L\'essor de l\'intelligence artificielle générative\n\nDepuis l\'émergence des grands modèles de langage (LLM) à partir de 2022, l\'intelligence artificielle générative s\'est imposée comme l\'une des ruptures technologiques les plus significatives de la décennie. Des entreprises comme OpenAI, Google DeepMind ou Anthropic ont investi des milliards de dollars dans le développement de systèmes capables de produire du texte, des images, du code ou encore de la musique à partir de simples instructions en langage naturel.\n\n### Comment ça fonctionne ?\n\nLes modèles génératifs reposent sur une architecture appelée **transformer**, introduite par Google en 2017. Ces réseaux de neurones sont entraînés sur des corpus massifs de données — des centaines de milliards de mots issus du web, de livres, d\'articles scientifiques — afin d\'apprendre les structures statistiques du langage.\n\nLe processus d\'entraînement peut se décomposer ainsi :\n\n- **Pré-entraînement non supervisé** : le modèle apprend à prédire le mot suivant dans une séquence\n- **Ajustement supervisé (fine-tuning)** : des annotateurs humains guident le modèle vers des réponses plus utiles et plus sûres\n- **RLHF (Reinforcement Learning from Human Feedback)** : un mécanisme de récompense affine le comportement du modèle\n\n### Des usages qui se multiplient\n\nLes applications concrètes sont déjà nombreuses. Dans le domaine médical, des modèles assistent les radiologues dans l\'analyse d\'images. Dans l\'industrie logicielle, GitHub Copilot est utilisé par plus de un million de développeurs pour accélérer l\'écriture de code. Dans l\'éducation, des tuteurs IA personnalisés commencent à faire leur apparition dans les salles de classe.\n\n### Des questions éthiques en suspens\n\nL\'essor de ces technologies soulève néanmoins des questions fondamentales : propriété intellectuelle des données d\'entraînement, risques de désinformation, impact sur l\'emploi, biais algorithmiques. Des régulateurs en Europe et aux États-Unis travaillent activement à encadrer ces usages, avec notamment l\'**AI Act européen**, entré en vigueur en 2024.\n\nIl est probable que les prochaines années seront décisives pour déterminer dans quelle mesure ces outils transformeront durablement notre rapport au travail et à la création.',
 '2024-01-15', 1, 1),

-- Article 2 : catégorie Société (id=2), auteur id=2
('La solitude à l\'ère des réseaux sociaux',
 '**Paradoxe de notre époque** : alors que nous sommes plus connectés que jamais, les études montrent une hausse alarmante du sentiment de solitude, notamment chez les jeunes adultes.',
 '## La solitude à l\'ère des réseaux sociaux\n\nEn 2023, l\'Organisation mondiale de la santé qualifiait la solitude de **problème de santé publique mondiale**, estimant qu\'un adulte sur quatre en souffre de manière chronique. Ce constat interpelle d\'autant plus qu\'il coïncide avec une expansion sans précédent des outils de communication numérique.\n\n### Un paradoxe bien documenté\n\nDe nombreuses études longitudinales, notamment celles menées par l\'Université de Pittsburgh et l\'Université de Pennsylvanie, ont établi une corrélation entre usage intensif des réseaux sociaux et dégradation du bien-être émotionnel. Les mécanismes identifiés sont multiples :\n\n- **La comparaison sociale** : la mise en scène permanente de soi sur Instagram ou TikTok génère des comparaisons anxiogènes\n- **La substitution relationnelle** : l\'interaction numérique tend à remplacer, plutôt qu\'à compléter, les échanges en face-à-face\n- **Le phénomène du FOMO** (*Fear of Missing Out*) : la peur de manquer quelque chose alimente une consultation compulsive des flux d\'actualité\n\n### Une génération particulièrement touchée\n\nLa génération Z — née entre 1997 et 2012 — est celle qui a grandi avec un smartphone en main. Paradoxalement, c\'est aussi celle qui déclare le plus souvent se sentir seule. Jean Twenge, psychologue à l\'Université d\'État de San Diego, a analysé des dizaines d\'années de données sur le bien-être des jeunes Américains. Ses travaux, publiés dans *iGen* (2017), montrent une rupture nette à partir de 2012, coïncidant avec la démocratisation des smartphones.\n\n### Des pistes de réponse\n\nFace à ce constat, des voix s\'élèvent pour repenser notre rapport aux écrans. Certaines villes expérimentent des **espaces de reconnexion sociale** : bibliothèques réaménagées, cafés sans wifi volontaire, initiatives de voisinage. Des entreprises tech commencent elles-mêmes à intégrer des fonctionnalités de limitation du temps d\'écran, sous la pression réglementaire et sociétale.\n\nLa technologie n\'est pas en soi la cause de la solitude moderne — les facteurs économiques, urbains et culturels jouent un rôle tout aussi déterminant. Mais l\'enjeu est désormais de concevoir des outils numériques qui favorisent le lien authentique plutôt que son simulacre.',
 '2024-02-20', 2, 2),

-- Article 3 : catégorie Histoire/Langues (id=3), auteur id=1
('Le latin, une langue morte toujours vivante',
 '**Lingua mortua ?** Loin d\'avoir disparu, le latin continue d\'irriguer nos langues, notre droit, notre médecine et même l\'internet. Plaidoyer pour une langue injustement négligée.',
 '## Le latin, une langue morte toujours vivante\n\nOn dit du latin qu\'il est une « langue morte ». L\'expression est commode, mais trompeuse. Car si le latin ne se parle plus dans les marchés ou les cafés — le Vatican mis à part, où il demeure langue officielle —, il n\'a jamais cessé de structurer nos façons de penser, d\'écrire et de nommer le monde.\n\n### Un héritage omniprésent\n\nLe français est, pour l\'essentiel, du latin transformé. Plus de **60 % du vocabulaire français** est d\'origine latine directe, auxquels s\'ajoutent les nombreux mots empruntés au grec via le latin. Les langues romanes — espagnol, portugais, italien, roumain, catalan — partagent ce même héritage, faisant du latin la matrice d\'une famille linguistique parlée aujourd\'hui par plus de 900 millions de personnes.\n\nMais l\'influence du latin dépasse les frontières de la Romania. L\'anglais, langue germanique, a massivement emprunté au latin via le français normand après 1066 : des termes comme *justice*, *liberty*, *nation* ou *parliament* en sont des exemples directs.\n\n### Dans les disciplines savantes\n\nLe latin reste la lingua franca de plusieurs domaines :\n\n- **En médecine et biologie** : la nomenclature anatomique (*tibia*, *radius*, *scapula*) et la taxonomie des espèces (*Homo sapiens*, *Panthera leo*) sont entièrement latines ou latinisées\n- **En droit** : des expressions comme *habeas corpus*, *in absentia*, *bona fide* ou *de facto* structurent le vocabulaire juridique international\n- **En liturgie** : la messe tridentine, célébrée par des millions de catholiques traditionalistes dans le monde, se dit intégralement en latin\n\n### Une renaissance inattendue\n\nContre toute attente, le latin connaît un regain d\'intérêt depuis une vingtaine d\'années. Des méthodes d\'apprentissage actif inspirées de la didactique des langues vivantes — comme la méthode *Lingua Latina per se Illustrata* de Hans Ørberg — permettent à des milliers d\'apprenants de lire Virgile ou Cicéron avec plaisir.\n\nSur internet, des communautés latines actives échangent en latin sur Reddit, Discord ou X. Des podcasts en latin — comme *Quomodo Dicitur* ou *Latin per Diem* — réunissent des auditeurs sur tous les continents.\n\n### Pourquoi l\'étudier encore ?\n\nApprendre le latin, c\'est acquérir une clé de lecture extraordinaire : comprendre la grammaire romane, enrichir son vocabulaire, aiguiser son sens de l\'analyse syntaxique. C\'est aussi s\'inscrire dans une continuité culturelle de deux mille ans — de César à Montaigne, d\'Ovide à Newton, qui rédigeait ses *Principia Mathematica* en latin.\n\nPlutôt qu\'une langue morte, le latin est peut-être la plus vivace des langues discrètes.',
 '2024-03-10', 3, 1);

-- Images
INSERT INTO `image` (`url`) VALUES
('/images/articles/cat-taking-a-selfie.webp'),
('/images/articles/femme-travaillant-de-la-maison-avec-ses-chats.webp'),
('/images/articles/mignon-chaton-jouant.webp'),
('/images/articles/thats-funny.webp');

-- Liaisons image_article
INSERT INTO `image_article` (`id_image`, `id_article`) VALUES
(1, 1),
(4, 1),
(2, 2),
(3, 3);